### ISSUE TITLE
Broken tray icon since last update

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.telegram.desktop#53]
It seems that the last update somehow broke the Telegram tray icon. It now disappears after a few minutes and reappears only when Telegram is manually killed and started again.

**Comment by grulja** [comment]
I pushed some changes now and new version is now being build, can you try later once https://flathub.org/builds/#/builders/2/builds/7528 is done?

**Comment by AsciiWolf** [comment]
Thanks, it seems to work fine now!

**Comment by AsciiWolf** [comment]
Oops, not fixed. The tray icon disappeared again after some time. :-(

**Comment by cho2** [comment]
No tray icon since last update

``
flatpak info org.telegram.desktop/x86_64/stable
Ref: app/org.telegram.desktop/x86_64/stable
ID: org.telegram.desktop
Arsitektur: x86_64
Cabang: stable
Asal: flathub
Tanggal: 2019-01-19 11:39:45 +0000
Subjek: Re-enable libappindicator support for native notifications (52564a7b)
Komit: de7cc2ebb3010037870269168d37b78291ca708ca79aaa1287b403cebcce8eb4
Induk: 0000a840a3b38e4b963363ce2142fb7804fdff34e379077792d274240201518f
Lokasi: /var/lib/flatpak/app/org.telegram.desktop/x86_64/stable/de7cc2ebb3010037870269168d37b78291ca708ca79aaa1287b403cebcce8eb4
Ukuran terpasang: 59,4 MB
Runtime: org.kde.Platform/x86_64/5.12
```

**Comment by shastry** [comment]
No tray here at all (no appearing and disappearing).

I get this message on startup:

`failed to register service "org.kde.StatusNotifierItem-3-3"`

**Comment by grulja** [comment]
What desktop do you use? I remember we fixed this in KNotifications (KDE Plasma) with this commit:
https://cgit.kde.org/knotifications.git/commit/?id=2b0b904ee0e986ea0a96a8f54e1522e492885ffe

**Comment by gasinvein** [comment]
Tray icons for most Qt apps don't work for me, either. I have to allow ownership of ` org.kde.StatusNotifierItem-2-1` bus name for the app to make the icon appear.
flathub/org.quassel_irc.QuasselClient#1 looks related.

**Comment by shastry** [comment]
> What desktop do you use? I remember we fixed this in KNotifications (KDE Plasma) with this commit:
> https://cgit.kde.org/knotifications.git/commit/?id=2b0b904ee0e986ea0a96a8f54e1522e492885ffe

Gnome 3.30.2 with [appindicator extension](https://extensions.gnome.org/extension/615/appindicator-support/).

Telegram tray icon was working fine earlier this month, before the last few updates.

Trays of other apps (skype, slack) work fine, but I guess they are not Qt based.

**Comment by cho2** [comment]
Now showing after updating `org.kde.Platform/x86_64/5.12` this morning

**Comment by gasinvein** [comment]
Still not working for me, `failed to register service "org.kde.StatusNotifierItem-2-1"`. Fedora 29, Gnome 3.30.2

**Comment by grulja** [comment]
Hmm, that's all probably because I changed telegram to use QSystemTrayIcon instead of libappindicator for tray icon, which in my opinion should be used anyway. I would like to get rid of libappindicator completely from telegram, but that's not possible without rewriting notifications. The only thing that can be done is probably to patch Qt to use same approach we have in KNotifications. I will look into this later. You can workaround this by allowing that DBus service.

**Comment by pgera** [comment]
This is broken on unity as well.

**Comment by grulja** [comment]
I pushed a new update to 1.5.8 and I re-enabled libappindicator support for tray icon (at least I hope I did). Can you verify it works for you? It will be available once https://flathub.org/builds/#/builders/2/builds/7670 is done.

**Comment by shastry** [comment]
Works now. Thanks!

**Comment by AsciiWolf** [comment]
It is unfortunately still broken on my system (GNOME Shell 3.30; Fedora 29) - Telegram icon disappears after some time. :-(

**Comment by grulja** [comment]
I don't think the icon disappearence is a bug in Telegram.

**Comment by AsciiWolf** [comment]
@grulja What bug is it then? It worked fine before.

I forgot to add that I use GNOME Shell 3.30 (on Fedora 29) with Topicons Plus.

**Comment by shastry** [comment]
@AsciiWolf Have you tried the [(K)StatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) extension?

I remember having similar weird issues with topicons and other apps before I moved away from the legacy tray icons to statusnotifier/appindicator extension.

**Comment by AsciiWolf** [comment]
@shastry I tried (K)StatusNotifierItem multiple times, but had issues (crashes and other weird behavior) with it every time. :( Also, it doesn't seem to support the legacy tray icons, only the AppIndicator ones.
