### ISSUE TITLE
Telegram crashes when clicking attach since last update

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.telegram.desktop#54]
When clicking the attach symbol to attach a file to a chat Telegram now crashes and quits. I believe before the previous Telegram update the xdg-desktop-portal file chooser would instead be shown.

In the console I get the following output.
```
(Telegram:2): GLib-GIO-CRITICAL **: 01:10:07.123: g_unix_is_system_fs_type: assertion 'fs_type != NULL && *fs_type != '\0'' failed

(Telegram:2): GLib-GIO-CRITICAL **: 01:10:07.123: g_unix_is_system_device_path: assertion 'device_path != NULL && *device_path != '\0'' failed
```

System info
```
$ lsb_release -rd
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
$ flatpak --version
Flatpak 1.0.1
$ apt-cache show xdg-desktop-portal | grep Version
Version: 0.11-1
```

**Comment by grulja** [comment]
Should be hopefully fixed with https://github.com/flathub/org.telegram.desktop/commit/f9041d1f765fa03f048a0f9cb38d052130468bb7.

**Comment by ahayzen** [comment]
@grulja Unfortunately this still occurs for me with the update, I have attached a gdb backtrace (i tried to install `org.kde.Sdk.Debug` to get more symbols but it is so large the download keeps failing :-( )

```
(Telegram:5): GLib-GIO-CRITICAL **: 23:58:48.051: g_unix_is_system_fs_type: assertion 'fs_type != NULL && *fs_type != '\0'' failed

(Telegram:5): GLib-GIO-CRITICAL **: 23:58:48.051: g_unix_is_system_device_path: assertion 'device_path != NULL && *device_path != '\0'' failed

Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
0x00007ffff5ef665e in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff5ef665e in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff1abf315 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#2  0x00007ffff1ac037f in g_unix_is_mount_path_system_internal () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007ffff1ac05e8 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff1ac353f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007ffff19d5bd7 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff19b7a78 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff19b91b5 in g_object_new_with_properties () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff19b9d71 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff1aac8f4 in g_volume_monitor_get () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007ffff2123d85 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff19d5bd7 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff19b7a78 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff19b950d in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff1fcc32a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff1fcee13 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff63f1e75 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff63f2f19 in g_markup_parse_context_parse () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff1fcf81e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff1fca66c in gtk_builder_extend_with_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff223433f in gtk_widget_init_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff207598f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff19d5bd7 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff19b7a78 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff19b950d in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff1fcc32a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff1fcd915 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff1fcf3ed in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff63f1fb2 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff63f30d6 in g_markup_parse_context_parse () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff1fcf81e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff1fca66c in gtk_builder_extend_with_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff223433f in gtk_widget_init_template () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff206cdf2 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff19d5bd7 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff19b7a78 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff19b99ee in g_object_new_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff19b9d4d in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff206d908 in gtk_file_chooser_dialog_new () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff261758d in ?? () from /usr/lib/plugins/platformthemes/libqgtk3.so
#40 0x00007ffff261bc40 in ?? () from /usr/lib/plugins/platformthemes/libqgtk3.so
#41 0x00007ffff31c4ea8 in ?? () from /usr/lib/plugins/platformthemes/libqxdgdesktopportal.so
#42 0x00007ffff78c5e3d in QDialogPrivate::platformHelper() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007ffff78d805b in QFileDialogPrivate::init(QUrl const&, QString const&, QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007ffff78d84e6 in QFileDialog::QFileDialog(QFileDialogArgs const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007ffff78d8a1d in QFileDialog::getOpenFileUrls(QWidget*, QString const&, QUrl const&, QString const&, QString*, QFlags<QFileDialog::Option>, QStringList const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007ffff78d8ca0 in QFileDialog::getOpenFileNames(QWidget*, QString const&, QString const&, QString const&, QString*, QFlags<QFileDialog::Option>) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00005555562e12d5 in FileDialog::internal::GetDefault(QPointer<QWidget>, QStringList&, QByteArray&, QString const&, QString const&, FileDialog::internal::Type, QString) ()
#48 0x00005555568691de in Platform::FileDialog::Get(QPointer<QWidget>, QStringList&, QByteArray&, QString const&, QString const&, FileDialog::internal::Type, QString) ()
#49 0x00005555562e052a in ?? ()
#50 0x00007ffff6c25252 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007ffff70d6a42 in QGuiApplication::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#52 0x00007ffff76e025f in QApplication::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007ffff76da621 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007ffff76e1bd0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x0000555556be2d72 in Application::notify(QObject*, QEvent*) ()
#56 0x00007ffff6bfa9e9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#57 0x00007ffff6bfd9e7 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#58 0x00007ffff6c4fb43 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#59 0x00007ffff63ee61e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#60 0x00007ffff63ee8b8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#61 0x00007ffff63ee950 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#62 0x00007ffff6c4f153 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#63 0x00007ffff6bf96bb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#64 0x00007ffff6c01822 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#65 0x00005555562e74cc in Core::Launcher::executeApplication() ()
#66 0x00005555562e7596 in Core::Launcher::exec() ()
#67 0x00005555560802e6 in main ()
(gdb) info threads
  Id   Target Id                Frame 
* 1    LWP 5 "Telegram"         0x00007ffff5ef665e in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
  2    LWP 10 "QThread"         0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  3    LWP 11 "QXcbEventQueue"  0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  4    LWP 12 "QDBusConnection" 0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  5    LWP 13 "Thread (pooled)" 0x00007ffff6388349 in pthread_cond_timedwait () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
  6    LWP 14 "Thread (pooled)" 0x00007ffff6388349 in pthread_cond_timedwait () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
  7    LWP 15 "Thread (pooled)" 0x00007ffff6388349 in pthread_cond_timedwait () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
  8    LWP 16 "Thread (pooled)" 0x00007ffff6388349 in pthread_cond_timedwait () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
  11   LWP 19 "QThread"         0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  12   LWP 20 "QThread"         0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  13   LWP 21 "QThread"         0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  15   LWP 23 "Telegra:disk$0"  0x00007ffff6387f5c in pthread_cond_wait () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
  16   LWP 24 "MTP::internal::" 0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  17   LWP 25 "Qt bearer threa" 0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
  20   LWP 28 "gmain"           0x00007ffff5f556f1 in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
```

**Comment by TingPing** [comment]
This is a runtime bug, fdo already updated fixing it but kde might require a rebuild.

**Comment by ahayzen** [comment]
OK, can this bug be reopened to track the issue?

**Comment by jurf** [comment]
Nope, not here.

**Comment by ahayzen** [comment]
Could it be related to having an older xdg-desktop-portal ?  eg I only have 0.11 from Ubuntu 18.04.

**Comment by ahayzen** [comment]
Or as TingPing said it was a runtime bug, did he mean that the kde runtime needs to be rebuilt to get the fix not the app ?

**Comment by TingPing** [comment]
> Or as TingPing said it was a runtime bug, did he mean that the kde runtime needs to be rebuilt to get the fix not the app ?

This is what I am referring to: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/commit/79106b78e4f11f66365c620661a73f7d81d959b6

**Comment by cho2** [comment]
On my telegram, it happen after https://github.com/flatpak/flatpak/issues/2558#issuecomment-455270868 fixed. 
Flatpak 0.10.4, openSUSE Leap 15.0

```
flatpak info org.telegram.desktop/x86_64/stable
Ref: app/org.telegram.desktop/x86_64/stable
ID: org.telegram.desktop
Arsitektur: x86_64
Cabang: stable
Asal: flathub
Tanggal: 2019-01-19 11:39:45 +0000
Subjek: Re-enable libappindicator support for native notifications (52564a7b)
Komit: de7cc2ebb3010037870269168d37b78291ca708ca79aaa1287b403cebcce8eb4
Induk: 0000a840a3b38e4b963363ce2142fb7804fdff34e379077792d274240201518f
Lokasi: /var/lib/flatpak/app/org.telegram.desktop/x86_64/stable/de7cc2ebb3010037870269168d37b78291ca708ca79aaa1287b403cebcce8eb4
Ukuran terpasang: 59,4 MB
Runtime: org.kde.Platform/x86_64/5.12
```
```
flatpak info org.freedesktop.Sdk/x86_64/18.08
Ref: runtime/org.freedesktop.Sdk/x86_64/18.08
ID: org.freedesktop.Sdk
Arsitektur: x86_64
Cabang: 18.08
Asal: flathub
Tanggal: 2019-01-16 22:58:51 +0000
Subjek: Export org.freedesktop.Sdk
Komit: c3f62b801fec84408ad169b44bcea9b30e2acf7881727045a24b3953ff0de791
Induk: 2daf7cdd062582dc72fed0b56670604a9a4c8f0a1697a6c5cad22978350e43ac
Lokasi: /var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/18.08/c3f62b801fec84408ad169b44bcea9b30e2acf7881727045a24b3953ff0de791
Ukuran terpasang: 3,9 GB
```

**Comment by TingPing** [comment]
@cho2 	because `org.kde.Platform//5.12` is what needs rebuilt.

**Comment by grulja** [comment]
The problem was in glib, shouldn't it be fixed with just simple update of freedesktop runtime? I don't think we need rebuild of KDE runtime.

**Comment by grulja** [comment]
Right, I didn't realize that, I lived in assumption that FDO is installed as base for KDE. I'll ask Aleix to do the rebuild.

**Comment by ahayzen** [comment]
@grulja I just tried with the updated runtime and I'm able to now click attach files using portals \o/ :+1:

**Comment by LeoBoudet** [comment]
Same bug here since the last update (debian buster).
